### ISSUE TITLE
Increase maximum book count beyond 100

### ISSUE THREAD

**Issue by brianpipa** [brianpipa/overreader-issues#10]
Right now the limit is 100 thanks to the RSS feed. Look into increasing this to some sane but usable limit. May want to get the  [mutithreading in place first](https://github.com/brianpipa/overreader-issues/issues/4)

**Comment by brianpipa** [comment]
v1.6  -made the limit configurable - deployed it with a 400 limit

**Comment by collinbarrett** [comment]
It _seems_ the RSS feed from Goodreads only shows up to 100 books. Based on your last comment, did you find a way to paginate the RSS feed so that you can search up to 400? Can you share how you are paginating the Goodreads RSS feed?

**Comment by brianpipa** [comment]
@collinbarrett Sorry for the delay in answering. I just saw this. Yes. By default it serves up 100 but it supports pagination so I just changed my code to read each page like:
`return String.format("https://www.goodreads.com/review/list_rss/%s?shelf=%s&page=%s&per_page=%s", userId, shelf, pageNumber, RSS_PER_PAGE);`

I arbitrarily limited it to 400. No real reason other than it takes a while to process that many. I created an Amazon Lambda to process the books (once I have the full list from GR) though and that does make it much faster. I just need to deploy it.

And yeah - managing large lists in GR isn't easy. There IS a way to do it that isn't too bad - i wanted to do the same at one point and found it in GR. it's called batch edit in GR.

**Comment by collinbarrett** [comment]
thanks! makes sense. I'mma hold out for awhile to see if you have the chance to / decide to raise the limit from 400. but, if my reading list dwindles, I'll look at batch edit to get my want-to-read under the limit.

thanks again for the fantastic app.

**Comment by brianpipa** [comment]
Send me your Goodreads userid and let me see what I can do. You can email it to me directly if you want.

**Comment by collinbarrett** [comment]
https://www.goodreads.com/review/list/137035410-collin-barrett?shelf=to-read

**Comment by brianpipa** [comment]
@collinbarrett  Wow - 906 books. I'm working on some KU Browser improvements today but I'll see if I can hook you up tomorrow.

**Comment by collinbarrett** [comment]
Thanks! I'm sure I'll never read them all, but what is available via Libby from my library strongly nudges me as to which ones I read. Overreader makes it so much easier to find those!

**Comment by collinbarrett** [comment]
I was able to fairly easily create `to-read-batch-x` sub-lists with Goodreads' Batch Edit feature to copy my `to-read` list into <=400 lists for Overreader. That worked! https://www.goodreads.com/review/list/137035410-collin-barrett

Thanks again for the great tool!

**Comment by brianpipa** [comment]
@collinbarrett  I just increased shelf size to 800
