### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by collinbarrett** [brianpipa/overreader-issues#14]
Not _at all_ an issue, but I just wanted to say THANK YOU for this tool! I've been looking for something like this for a while, and I was actually just about to try to build exactly what you have here myself.

Definitely a bookmark, and I much appreciate it.

I'm a .NET dev, so not sure I'd be of much coding help with this stack. But, I'd love to contribute at some point if I could ever help.

Great work.

**Comment by collinbarrett** [comment]
My forte is backend work. Frontend is the same area in which I'd love support on my primary hobby project as well. So, I may not be able to help in that area in the near future.

But, again, awesome tool. I've shared it with a bunch of friends who I know use Goodreads. Helping you growth hack it a bit whether you wanted it or not. 😆

**Comment by brianpipa** [comment]
Awesome! Thanks!
