### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by collinbarrett** [brianpipa/overreader-issues#15]
I don't think you need HTTPS for security for what you are doing, necessarily, but I know it affects SEO. And honestly, it's a bit tricky even to get the site to load in my primary Firefox instance since I have it locked down to only load HTTPS sites.

**Comment by brianpipa** [comment]
Yep - agreed - i just haven't gone through the trouble of setting up the certs yet.

**Comment by brianpipa** [comment]
@collinbarrett I just looked and the way I'm using AWS, it will cost me $40/month to be able to use https. I'm going to poke around and see if there is another cheaper way to do it, but right now, there is no way i can spend that money. There must be a cheaper way to accomplish this though.

**Comment by brianpipa** [comment]
Ok, I figured out the cheap way to do it - I may give it a go this weekend. For (my) reference:

- https://www.thomasvitale.com/https-spring-boot-ssl-certificate/
- https://www.baeldung.com/spring-boot-https-self-signed-certificate
- https://letsencrypt.org/

**Comment by collinbarrett** [comment]
Yeah, I wouldn't pay $40/mo either.

One other easy button option I've used in the past is routing your site through Cloudflare. Their free plan allows client->Cloudflare connections to be HTTPS with a flip of a button. Cloudflare->server connections can also be HTTPS for free, but you have to install the cert on the server (a bit more fiddling).

**Comment by brianpipa** [comment]
DONE - it's now running on HTTPS and it redirects automatically! Woohoo!!!!

done and pushed - 3.1.9
