### ISSUE TITLE
Consider open-sourcing the code

### ISSUE THREAD

**Issue by collinbarrett** [brianpipa/overreader-issues#16]
> Code stored in [Bitbucket](https://bitbucket.org/), for now. Will probably switch to Github eventually

[via](http://overreader.com/view/tech)

It's your prerogative, and feel free to close this issue if you have no desire to immediately. But I'd love to see the codebase open-sourced. The immediate reason would be if something happens to both you and your live site, I'd love for somebody else to be able to stand up a new instance of it.

**Comment by brianpipa** [comment]
Ha - that's very flattering! I need to update that page - I have moved the code to github, but ti's in a private repo. I have no current plans to open source it. Maybe in the future though.
